### ISSUE TITLE
projection wrong on S-N pass

### ISSUE THREAD

**Issue by marianzb** [altillimity/SatDump#100]
projected images from polar satelite are wrong during northward pass (nightly). This is from Meteor M2 LRPT, daytime is ok, nighttime has wrong position and shape.
![m1](https://user-images.githubusercontent.com/3983614/155693454-4498c292-1b49-458d-ba2e-c5bab5d3b91d.jpg)
![m2](https://user-images.githubusercontent.com/3983614/155693459-c6df79f4-d446-4dee-8d65-161628b9d518.jpg)
![m3](https://user-images.githubusercontent.com/3983614/155693462-b7f468cd-34df-4f31-8402-50fa1714b7a5.jpg)
![m4](https://user-images.githubusercontent.com/3983614/155693464-a258fd76-b9c6-4fcb-b5e0-5e78e2776435.jpg)
![m5](https://user-images.githubusercontent.com/3983614/155693468-131a8ed5-e088-46b5-9196-46ae02f32128.jpg)
![m6](https://user-images.githubusercontent.com/3983614/155693469-aead53ff-522e-4d2e-9b3f-e54eeb86b3ab.jpg)
![m7](https://user-images.githubusercontent.com/3983614/155693470-9caeb07d-e936-4fb1-8984-ff18a52488dc.jpg)
.

**Comment by Aang23** [comment]
To make sure : were all those projections done with data processed on the (UTC) day of reception? They have to be as M2 does not transmit any sort of day indicator.

This looks more like a LRPT-specific issue. It is known to work with the rest.

**Comment by K4KDR** [comment]
I see the same issue "sometimes" with S-to-N (that is nighttime here in U.S.) passes.  However, at times the projection is correct.  I am only using Meteor-M2 LRPT 'live processing'.   

I have never noticed if the time was past 0000 UTC - will watch that going forward to see if the "good" projections are before 0000 UTC and the reversed projections are after 0000 UTC or not.

**Comment by marianzb** [comment]
Thanks for this hint, its caused by processing on next day. Now I have processed it same day as it was recorded and its correct.
I would have a suggestion if M2 decoded time is in 'future' according current UTC time, there could be subtracted one day. It will solve this problem at least for case when processing and recording were within 24 hours.

![m8](https://user-images.githubusercontent.com/3983614/155797646-06e3ad21-58ef-4e02-aee2-23f3ec7dcf34.jpg)
![m9](https://user-images.githubusercontent.com/3983614/155797656-370f68dc-ab59-4bf7-85b9-10b271a7504a.jpg)

**Comment by K4KDR** [comment]
Actually, I see now that my issue is **not** related to time-of-day.

Both the live capture & the final processing were done before 0000 UTC.   If you would like this to move to a separate issue, please let me know.

As is normal with south-to-north passes, the Meteor-M2 LRPT image is inverted.  However, the green border outline is not.

The result is that the image is correct (inverted) but the green borders are not.  As I mentioned previously, about one time out of every 10, the orientations will match.  I do not know what is different about the times that they match correctly.

This image should render as being over North America.

![MSU-MR-5-EQU-PROJ-north-south](https://user-images.githubusercontent.com/19886368/155817992-b7680023-cf9c-4801-bc3f-038ae2d18866.png)

**Comment by Aang23** [comment]
Wait. I forgot - M2 is not in UTC time but Moscow time, unlike M2-2.
Would that explain your issues?

**Comment by K4KDR** [comment]
I believe you are correct.  I am now on the same UTC day as Moscow time (26-Feb) and I just ran last night's .CADU file through the 'Offline Processing' tab.  See below - the projection is correct.     Other than changing my **system time zone** to match Moscow time, do you have any suggestion for how to render these correctly when using 'Live Processing'?  Thanks!

![MSU-MR-5-EQU-PROJ-crop](https://user-images.githubusercontent.com/19886368/155848050-4aa6de16-7856-4cb4-83a6-7c44aa3495f2.png)

**Comment by K4KDR** [comment]
Did a test on tonight's Meteor-M2 pass to see if setting my system time/date zone to Moscow would result in the border overlay being correct.  It did not.

Before the SatDump-UI app was run, my system timezone was set to Moscow (shown here at the end of processing, but it was set prior to running the application):

![system-date](https://user-images.githubusercontent.com/19886368/155862196-7430dbc8-1c4e-43b8-89c9-217e702ad2e1.png)

... but the end result after "Live Processing' was that the border overlay was reversed:

![MSU-MR-5-EQU-PROJ-crop](https://user-images.githubusercontent.com/19886368/155862214-1ce40de3-59b2-44cd-adab-45b21c8bfc4b.png)

... I noticed something that I cannot explain.  Even though my system time, as well as the time-stamps that run down the left side of the terminal window that SatDump was run from, all show Moscow time, the post-pass processing run by SatDump created its folder structure using UTC time:

![folder-creation](https://user-images.githubusercontent.com/19886368/155862251-95a1f2d2-bc8b-481f-b9b0-c52ab82e7652.png)

... so, I hope that this is helpful to perhaps explain the day mismatch from Moscow time & the resulting inverted border overlay on these late night south-to-north passes.  Many thanks!
