### ISSUE TITLE
error : Could not set SDR frequency

### ISSUE THREAD

**Issue by YD9CKH** [altillimity/SatDump#107]
Can someone tell me how to resolve the error. Im using Satdump v0.0.38 for Windows, When try to START Live processing for pipeline : GK-2A LRIT, i get error  " (E) Could not set SDR frequency " and the apps is stuck. 
Thank you,
![image](https://user-images.githubusercontent.com/76090141/163708124-42fbec14-7d51-48f1-acf1-39ff86f6d1a0.png)

**Comment by zeke800** [comment]
What SDR are you using?

**Comment by YD9CKH** [comment]
Hi,
Im using SDR V3 and my Windows is Windows 10 64bit

Thank you
Best Regards,

YD9CKH

**Comment by zeke800** [comment]
Hmm you mean the RTL SDR V3? I have one of those and it works quite well. Try running rtl-test and see if it works. Occasionally there have been faulty dongles. Does it work with SDR software such as SDR# or SDR++ ?
