### ISSUE TITLE
Meteor MN2 channels align

### ISSUE THREAD

**Issue by marianzb** [altillimity/SatDump#110]
Sometimes, quite often, there is problem with composing color picture from decoded channels. Original channels are decoded correcly, but 125 or 123 composite is wrong
![MSU-MR-1](https://user-images.githubusercontent.com/3983614/165702998-d9bcf1e8-31a9-4707-aebb-142650bdb606.png)
![MSU-MR-2](https://user-images.githubusercontent.com/3983614/165703004-e9e22f3a-158a-421b-b122-29341214befd.png)
![MSU-MR-3](https://user-images.githubusercontent.com/3983614/165703007-5dab6e10-9001-413a-9d0a-b1ef39eb6a59.png)
![MSU-MR-RGB-321](https://user-images.githubusercontent.com/3983614/165703013-09c883bc-0066-4a04-b439-6e5349ca6fe3.png)

here is attached also signal source, thanks
[cadu_source.zip](https://github.com/altillimity/SatDump/files/8580581/cadu_source.zip)
.

**Comment by marianzb** [comment]
another example
![ch123](https://user-images.githubusercontent.com/3983614/165704745-74a11ab4-fb4b-497b-8543-4494f329988e.png)
![MSU-MR-RGB-221-proj](https://user-images.githubusercontent.com/3983614/165704761-eaf3900b-66c1-439a-bab3-e77b565f93d5.png)
[cadu_source2.zip](https://github.com/altillimity/SatDump/files/8580650/cadu_source2.zip)

**Comment by zeke800** [comment]
Hmm... just looking at it it seems correct.
