### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by zeke800** [altillimity/SatDump#114]
Would it be possible to make the windows builds work again? The older ones are expired, and the release is old. It is now impossible to download the new version because for some reason it can't download SDRPlay.zip. However, the android builds work well. 

Run Invoke-WebRequest -Uri "https://files.altillimity.com/SDRPlay.zip" -OutFile D:\a\SatDump/sdrplay.zip
Invoke-WebRequest : Unable to connect to the remote server

Invoke-WebRequest -Uri "https://files.altillimity.com/SDRPlay.zip" -O 

CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by zeke800** [comment]
I now have a windows build here. https://github.com/zeke800/SatDump/actions/runs/2443641098

**Comment by ZbychuButItWasTaken** [comment]
Windows builds are generated again
