### ISSUE TITLE
Feature requests for satellites

### ISSUE THREAD

**Issue by kord1e** [altillimity/SatDump#121]
1) It would be very useful to have a check box option to rotate/flip satellite images automatically. This is needed when the satellites fly south to north. Some APT decoders have this feature.

**Comment by ZbychuButItWasTaken** [comment]
fixed in release

**Comment by Aang23** [comment]
@kord1e perhaps see if the new viewer system fits your needs? I'd consider this closed for now, as automatic rotation would only potentially make sense when offline-processing.
