### ISSUE TITLE
RTLSDR LNA gain not high enough.

### ISSUE THREAD

**Issue by JB-Micro** [altillimity/SatDump#125]
While testing out the new 1.0.0 version on Windows and Linux, I've noticed that while live processing in the recorder tab, the difference between max LNA gain and min LNA gain is insignificant, I can see 1 or 2 dB difference in the spectrum plot. I've been trying to use satdump to get GOES HRIT data and with my sawbird on and the dish pointed at the satellite, I can only see and decode the signal with the AGC turned on. There's a clear difference in the spectrum plot too between max LNA gain and AGC.

 This is all using RTLSDR blog V3 with nooelec Sawbird. The issue is happening on both Windows and Linux versions. I've been trying to find where the gain is set in the code but haven't been able to so far. I saw someone mention in the past that the gain should be multiplied by 10 and it wasn't happening in a previous version of satdump. Could that be the issue here?

![image](https://user-images.githubusercontent.com/77820878/190810783-66e27988-9eca-41c5-ade7-306f24f9097c.png)
This is with AGC set (no antenna connected).

![image](https://user-images.githubusercontent.com/77820878/190810742-f993ac79-a25d-4646-b7ed-5e7ab98955a2.png)
Max gain, no AGC (no antenna)

![image](https://user-images.githubusercontent.com/77820878/190810820-09687bf0-53ba-4549-ae21-dcf2f8ac39af.png)
Min gain, no AGC (no antenna)

**Comment by Aang23** [comment]
Yes, the x10 was the bug! Oops sorry! Just pushed a fix.
