### ISSUE TITLE
Viewer correction bug

### ISSUE THREAD

**Issue by sdrgeek** [altillimity/SatDump#128]
Hi, 
played with the photo viewer and found this bug: when the pictures get corrected, text gets stretched too.

![text bug](https://user-images.githubusercontent.com/81026491/190854269-c7039636-7775-4d70-b1a8-ec22eea45b3b.png)

**Comment by Aang23** [comment]
Oh, oops. That's an oversight. Gonna fix.

By the way just for info : the overlay being a bit off near cuts on the image is normal.

**Comment by Aang23** [comment]
![avhrr_3_composite_corborders](https://user-images.githubusercontent.com/23421917/190858411-dbccb4cd-fe90-40c4-9453-7a635eea4b64.jpg)

I'd call it fixed. Keep in mind correction exacerbates potential innacuracies on the sides.
