### ISSUE TITLE
Meteor LRPT image output?

### ISSUE THREAD

**Issue by K4KDR** [altillimity/SatDump#131]
Caveat - I could EASILY be missing an option or doing something incorrectly...

Just tried the v1.0 GUI for the first time & recorded a **VHF Meteor-M2 LRPT** pass.

When I ran the 'offline processing' to create images, I got one for each channel but not the combo images that used to appear automatically.

Am I not seeing an option, does the software need to be run (or built) with some special option, or what?  

HUGE thanks!!

-Scott,  K4KDR

**Comment by Aang23** [comment]
Well, now you either use the viewer to create them, or enable the "automatically process products" option in settings to do like it was before!

**Comment by K4KDR** [comment]
Ahh - thanks SO much.

I'll have to explore what's available on that viewer tab.    And my bad -  I didn't understand what "automatically process products" meant.

This can be closed - thanks!!
