### ISSUE TITLE
Icon entry in .desktop file lacks file extension

### ISSUE THREAD

**Issue by shuyuan-liu** [altillimity/SatDump#134]
The `Icon` entry in `satdump.desktop` lacks the `.png` file extension and it causes GNOME 42.4 to not show any icon for the program:

![Screenshot from 2022-09-19 20-43-33](https://user-images.githubusercontent.com/41851763/191106772-2b2044fc-64d0-4a15-9452-64e76edbf371.png)

The [freedesktop.org specification for desktop entries](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#entries) states that "if the name is an absolute path, the given file will be used", which probably means the file extension needs to be included. Once I added `.png` to the path, the icon showed fine.

**Comment by shuyuan-liu** [comment]
Curiously, the `.png` was there before but was removed in d9b8801908ab8009201651e0c5d513cea31ff501. Was it done for any particular reason?

**Comment by Aang23** [comment]
I'd guess back then I read it should not be provided and removed it. Thanks for reporting!

Do you want to submit a PR or should I fix it?

**Comment by shuyuan-liu** [comment]
Sorry I didn't expect such a fast reply — and thanks for the fix!

**Comment by Aang23** [comment]
No worries! Thanks!
