### ISSUE TITLE
Error starting the gui

### ISSUE THREAD

**Issue by Botox200** [altillimity/SatDump#137]
Compiled successfully, but got this message on start:

`terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be number, but is array
Abgebrochen (Speicherabzug geschrieben)`

OS: Kubuntu 20.04, kernel 5.15.0-48-generic

**Comment by Aang23** [comment]
Did you symlink all required files as mentioned in the README?
Eg, you should symlink/copy `satdump_cfg.json`, `pipelines` and `resources`.

**Comment by Botox200** [comment]
No, i installed it systemwide with
`sudo make install`

**Comment by Aang23** [comment]
Oh! Then that *is* an issue. Make install should be settings those up.

**Comment by Aang23** [comment]
@Botox200 Ok, this is probably because you had the old version installed previously. The old pipelines are not compatible and will cause this sort of errors.
