### ISSUE TITLE
Does SatDump account for doppler shift?

### ISSUE THREAD

**Issue by mmm545** [altillimity/SatDump#140]
or do i have to constantly re-tune it?

**Comment by Aang23** [comment]
It does not do "direct" doppler shift correction using the satellite's velocity (as that did not prove necessary on anything being decoded yet at all), but the demodulator WILL lock on the right frequency as long as the offset is not too big (too large being normally much bigger than doppler would ever be). So yes, it does.

The only downlink that may require some manual tuning right now is Stereo, but chances are that's not what you're going to be working with.

**Comment by mmm545** [comment]
Locking on the signal is what I meant, yes
Alright thank you very much
