### ISSUE TITLE
error: ‘ZSTD_c_compressionLevel’ was not declared in this scope

### ISSUE THREAD

**Issue by K4KDR** [altillimity/SatDump#142]
Hello!  Had no trouble building v1.0, but with the recent BlueWalker-3 update, I get the following on my Ubuntu 18.04 computer:

```
[ 25%] Building CXX object src-core/CMakeFiles/satdump_core.dir/core/config.cpp.o
/home/k4kdr/satdump/src-core/common/ziq.cpp: In constructor ‘ziq::ziq_writer::ziq_writer(ziq::ziq_cfg, std::ofstream&)’:
/home/k4kdr/satdump/src-core/common/ziq.cpp:27:46: error: ‘ZSTD_c_compressionLevel’ was not declared in this scope
             ZSTD_CCtx_setParameter(zstd_ctx, ZSTD_c_compressionLevel, zst_level);
```

**Comment by K4KDR** [comment]
Many thanks for the reply!

For anyone who finds this in the ISSUE history, the error was cleared by installing the latest **ZSTD** from:

https://github.com/facebook/zstd/releases/tag/v1.5.2

**Comment by ZbychuButItWasTaken** [comment]
Closed for now as seems it was just outdated zstd, could be reopened if needed
