### ISSUE TITLE
parts of image missing in 221 RGB composite

### ISSUE THREAD

**Issue by 1TechSupport1** [altillimity/SatDump#147]
So I've been trying to use satdump v1.0.0 and every time that  I get a pass and make a composite image a lot of the image goes missing but this did not seem to happen with v0.0.3B.
MSU-MR-1:
![MSU-MR-1](https://user-images.githubusercontent.com/70839549/195230546-4d69f5b6-40ff-49e3-867a-5281a6dc6648.png)
MSU-MR-2:
![MSU-MR-2](https://user-images.githubusercontent.com/70839549/195230141-bfdb15f2-bb66-4893-bd9d-90e6be8083cc.png)
MSU-MR-5:
![MSU-MR-5](https://user-images.githubusercontent.com/70839549/195230595-4e535cd9-f475-47ac-92ec-62c9709c1e82.png)

221 RGB composite:
![image](https://user-images.githubusercontent.com/70839549/195230188-36c50b1b-4351-4098-8848-5e31ca65d78d.png)

and the last pass that i attempted to decode was almost like a barcode, and i had 14db of peak snr that lasted for 3 minutes of the pass, I discarded it because lack of storage space.

I've gotten better images with less snr in the old version, and i used the same V-dipole at the same place.

**Comment by Aang23** [comment]
Hm. That's weird behaviour indeed. Do you have the files on hand? (frames / soft / baseband)

**Comment by Ajaykumar415** [comment]
No as it was a live decoding session.

**Comment by Aang23** [comment]
Live decoding should keep the .cadu file though?

**Comment by Ajaykumar415** [comment]
yup i do have the cadu file but can't upload it here, it seems git hub doesn't support this file format.

**Comment by RAD750** [comment]
It would look to me like you have some sort of processing power issue, watch cpu usage and if on Linux, make sure to compile SatDump properly or it will run very slow

**Comment by Ajaykumar415** [comment]
I am on windows, and I have set satdump to use CUDA and my computer does have a GTX1650Ti, i will check the GPU and CPU usage in the next pass. I will look into uploading the CADU file.

**Comment by ZbychuButItWasTaken** [comment]
Any update on the issue?

**Comment by Aang23** [comment]
Well, since there were no updates I will close this. Will re-open if necessary.
