### ISSUE TITLE
Remember last used input / output directories

### ISSUE THREAD

**Issue by shuyuan-liu** [altillimity/SatDump#15]
Currently every time we run SatDump we need to select the input file and output directory. The file / folder selection dialogue default to the current working directory, and when running SatDump from the build folder this is almost certainly incorrect. It would be nice if it's possible to make the input / output selection dialogues default to the last used directories.

**Comment by Aang23** [comment]
I would guess this goes along with integrating a more general settings / sate system to keep some user configuration. Might not do that until I've started moving out the UI part into its own general library.

satdump_core aims at being more of a library than containing the actual UI / etc code.
