### ISSUE TITLE
Unable to select 2nd OpenCL capable device

### ISSUE THREAD

**Issue by KentuckyFriedData** [altillimity/SatDump#152]
Device is shown in the logs here
![Screenshot 2022-10-14 185510](https://user-images.githubusercontent.com/31137660/196051430-c0a667fe-fadb-459a-9521-581e39c24a87.png)

but in SatDump v1.0.0 it is not shown
![Screenshot 2022-10-14 185528](https://user-images.githubusercontent.com/31137660/196051474-fc88e3da-f043-4353-9c9b-f972a38f7b71.png)

**Comment by Aang23** [comment]
Ok, that is an interesting one... Will have to check on Windows.

**Comment by Aang23** [comment]
Fixed.
