### ISSUE TITLE
No apk artifact of latest master build

### ISSUE THREAD

**Issue by M123-dev** [altillimity/SatDump#159]
(The apk in 1.0.0-beta doesn't work on my device so I wanted to try the latest master build)

The latest build on master isn't uploaded to artifacts anymore:

`Warning: No files were found with the provided path: $GITHUB_WORKSPACE/android/app/build/outputs/apk/debug/app-debug.apk. No artifacts will be uploaded.`

https://github.com/altillimity/SatDump/actions/runs/3306529847/jobs/5457487505

**Comment by Aang23** [comment]
Fixed
