### ISSUE TITLE
Issues installing following SatDump READMe.md

### ISSUE THREAD

**Issue by Kyynetic** [altillimity/SatDump#162]
Here is the error produced when cmake is ran...
<img width="432" alt="Screen Shot 2022-10-26 at 12 08 58" src="https://user-images.githubusercontent.com/110482062/198078463-50292015-8815-4ce4-98c0-110b9361eefd.png">

Here is the src-core/libs folder with jpeg present...
<img width="767" alt="Screen Shot 2022-10-26 at 12 10 21" src="https://user-images.githubusercontent.com/110482062/198078720-3efb6219-b519-42a6-92db-5c1bf6052d8c.png">

**Comment by ZbychuButItWasTaken** [comment]
Looks like you haven't followed the readme correctly.
`sudo apt install git build-essential cmake g++ pkgconf libfftw3-dev libvolk2-dev libjpeg-dev libpng-dev # Core dependencies. If libvolk2-dev is not available, use libvolk1-dev`

**Comment by Aang23** [comment]
Yep... SatDump bundles its own (modified) libjpeg to decompress some J2K variants. Actually I should probably drop the dep on libjpeg.

**Comment by Aang23** [comment]
Just removed the dependency, instead using the bundled one exclusively... I *have* to bundle it anyway as libjpeg-turbo on most systems does not have the required features (reading from a buffer, J2K, etc).

**Comment by Kyynetic** [comment]
I removed and recloned the satdump repository after your change and the cmake command works now much thanks!

**Comment by Aang23** [comment]
You're welcome!
