### ISSUE TITLE
GOES-R GRB crashes when used with live processing 

### ISSUE THREAD

**Issue by Lmello1** [altillimity/SatDump#163]
GOES-R GRB crashes seconds after starting live decoding. Multiple sources produce the same result.

**Comment by ZbychuButItWasTaken** [comment]
That's very weird, could you provide some more information? Mostly about your system (os, hardware and SDRs used), but also logs will be very useful!

**Comment by Aang23** [comment]
Hmmmm. Interesting about GRB. Does it work from a baseband though?

**Comment by Aang23** [comment]
Just did a quick check. Runs here. Maybe yet another Windows issue?
![Screenshot from 2022-10-26 22-49-45](https://user-images.githubusercontent.com/23421917/198134831-ea641a70-ff27-4ac4-bf5d-3159f26cecac.png)

**Comment by Lmello1** [comment]
OS: Windows 10
crashes on laptop and desktop with hackrf, RTL-SDR, and even trying to decode from a blank file.
Logs do not even show that the decoding has started, however I can upload one if you would like

**Comment by Aang23** [comment]
Fixed in https://github.com/altillimity/SatDump/commit/254b03b36971fc8efc66f773e91901ec9ca0ffec
