### ISSUE TITLE
Projection fail on METEOR-M LRPT

### ISSUE THREAD

**Issue by RAD750** [altillimity/SatDump#168]
The projection feature fails totally on Meteor-M LRPT when ran automatically as part of the decode.

If ran manually, it produces a corrupt projection (see screenshot)

Decoding was done with SatDump and the same day the pass occurred :))

Hardware (SDR/PC/OS)
Thinkpad X260 (Intel i5-6200u, Intel HD Graphics 520); RTL-SDR (operating on a .s file from SDR++) 

Version (Eg, 1.0.0, CI Build #171)
1.0.0 built about 30 minutes ago

Screenshots

Failed manual projection
![immagine](https://user-images.githubusercontent.com/12469744/198716071-2a89dbb9-8a9b-4824-bc9f-557d314b33ea.png)

CADUs and other data useful for debugging

[.s file from the pass](https://cdn.rgbcraft.com/altro/meteor_19-10-38_28-10-2022.s)

Thank you (and sorry for bothering you yet again) :smile: :heart:

**Comment by Aang23** [comment]
Fixed! 
![Screenshot from 2022-10-28 23-00-04](https://user-images.githubusercontent.com/23421917/198731533-2cf24081-144e-46a1-b3df-21466c4bf51f.png)
