### ISSUE TITLE
SatDump crashes on launch on RealmeUI 3.0 (Android 12)

### ISSUE THREAD

**Issue by Foxiks** [altillimity/SatDump#169]
When trying to run an app on Android 12, the app won't open. The screen goes dark for a couple of seconds and then the app closes.

Latest build (https://github.com/altillimity/SatDump/actions/runs/3349055107)

The parameters of the phone on which the test was performed:
Android 12
Snapdragon 855+
8 GB RAM
All permissions granted
Mobile internet mode

**Comment by Aang23** [comment]
Hmmmm. Mind trying with this APK? https://www.swisstransfer.com/d/de665f26-31e9-4d73-bd56-698733a02bcd

**Comment by Foxiks** [comment]
Yes! Give me a few minutes)

**Comment by Foxiks** [comment]
Yes, it works!
