### ISSUE TITLE
Crash when using Live Processing with Remote SpyServer

### ISSUE THREAD

**Issue by cm2esp** [altillimity/SatDump#17]
The program crashes when trying to connect to a remote spyserver on Live Processing mode. Same issue with GOES HRIT and NOAA HRPT. The remote server is on another device on the same local IP subnet. The spyserver app never received the connection request attempt from SatDump.

**Comment by Aang23** [comment]
I just tested. I can confirm the issue... Thanks!

**Comment by Aang23** [comment]
Fixed in an earlier commit.
