### ISSUE TITLE
zsh: illegal hardware instruction ./satdump-ui

### ISSUE THREAD

**Issue by benb0jangles** [altillimity/SatDump#177]
error on MacOs Monterey 12.6.1
mac mini 2012

Latest satdump (as of November 4th 2022) version https://github.com/altillimity/SatDump

when run satdump with:
`./satdump-ui`

get error:
`zsh: illegal hardware instruction ./satdump-ui`

**Comment by Aang23** [comment]
Rebuild FFTW-3 without the AVX2 = on flag?

**Comment by benb0jangles** [comment]
worked :)
