### ISSUE TITLE
FY-2H offset

### ISSUE THREAD

**Issue by sq7r0** [altillimity/SatDump#179]
Hi,

im not sure if this is possible to fix, but worth to mention. Have found an issue regarding Fengyun S-VISSR imagery which is offset every single frame received. I have drawn a line parallel to the south pole, to show how much the image is shifted every few hours. Any idea it could be fixed or its just a satellite sensor image shifted? There is a difference even between images from the same time of the day, different date. The offset makes the automatic processing pretty tricky
![image](https://user-images.githubusercontent.com/115694905/200410054-1f7613f4-2f85-463b-bc60-e17881de456e.png)
![image](https://user-images.githubusercontent.com/115694905/200410105-0369be6a-818b-4d14-98c5-d17c0592ed24.png)
![image](https://user-images.githubusercontent.com/115694905/200410171-f1413a62-518a-4463-a84f-512b4e3d639d.png)
cheers
Krzysztof

**Comment by Aang23** [comment]
That is unfortunately down to the satellite / format. I process images "putting the lines in the right spot" using counters it provides, but the Earth still moves around.

Perhaps if you could provide a few sample basebands of affected full disks I could see if there's something I can do. I could perhaps implement further processing to center it back.

Nice reception by the way! Out of curiosity, where are you located and what's your setup? Pretty good results on L3 etc.

**Comment by sq7r0** [comment]
Yup, i thought so, but worth to ask ;) Sure, I will upload some basebands within the same time period between them. Hope it helps. I have tried to use Sanchez on FY-2H but because of shift and different geometry/rotation its practically useless.

Thanks, I have just replaced 0,7 offset dish to 1.9m parabolic mesh dish on a tower to be able to catch those, as all geosats are low elevation from my point. There is a helix with sawbird lna and finally rspdx. My location is near Zbychu's, Warsaw/Poland. FY-2H is fine, but still get too much errors on GOES GVAR, the only one GOES available here - its about 5-6dB SNR

**Comment by Aang23** [comment]
Thanks! I also need to make projection files for FY-2H etc anyway so it will be useful either way.

Oh nice! That's pretty good. @ZbychuButItWasTaken was using a 1.8m for GVAR though, so chances are your feed needs to be linear and properly pointed. It's not an issue on ELEKTRO-L as it is RHCP but could really hurt you on GOES.

**Comment by ZbychuButItWasTaken** [comment]
5-6 db does sound about right for a circular feed, I was usually getting around 9db on my dish. That matches pretty well assuming 3db loss between circular and linear polarization

**Comment by sq7r0** [comment]
@ZbychuButItWasTaken i wish, but im getting maaany horizontal lines. Started to think there is something more wrong here, as some of those lines are on every capture, for example the white lines here below. Maybe its kind of live processing issue, i have to try this on another machine
![image](https://user-images.githubusercontent.com/115694905/200428608-fc575347-a53c-49d8-a53f-4129e984c751.png)
![image](https://user-images.githubusercontent.com/115694905/200428999-19760587-639a-49a6-a7d9-96fd88944db4.png)

**Comment by Aang23** [comment]
Those lines are due to bad data, so low SNR mainly. The white ones are due to the same lines on IR channels... So unfortunately I highly doubt a better PC would help much at all. @ZbychuButItWasTaken used to run it on Core2Quad just fine (back when things were much, much less optimized).

**Comment by sq7r0** [comment]
@Aang23 yea, but the same lines are on channel 1 but different time, which is strange im getting bad data every time at the same point.

![image](https://user-images.githubusercontent.com/115694905/200430913-7a3b1550-4738-4fb4-9d6c-e745b392268e.png)
![image](https://user-images.githubusercontent.com/115694905/200430956-7b5c79e2-75b3-457e-8cb0-4b9947e9faac.png)
![image](https://user-images.githubusercontent.com/115694905/200431154-d0aff178-bd68-4cb8-a051-cebc5c413229.png)

**Comment by Aang23** [comment]
Hmmm @sq7r0 perhaps if you can join the Matrix room (see the readme)? Will more practical to see what's going on there!
Though I actually have an idea now.

**Comment by sq7r0** [comment]
to have a better view of the shift i made a two day animation 

https://user-images.githubusercontent.com/115694905/200844309-9d95f892-73ff-4fcf-b8b7-09e367e73d11.mp4

**Comment by Aang23** [comment]
Yes so that definitely is the sat. Is the offset identical at the same time of day?

**Comment by sq7r0** [comment]
its close but nope
![image](https://user-images.githubusercontent.com/115694905/200855646-91be63bd-5f3e-418b-9b18-340896b472b4.png)
![image](https://user-images.githubusercontent.com/115694905/200855710-9824330a-d907-49af-946c-f2b5c4f07be2.png)
![image](https://user-images.githubusercontent.com/115694905/200855753-67791c3a-5cce-44fc-8c47-7aea2be57e3b.png)

**Comment by Aang23** [comment]
All that could really be done honestly is generating projections using TLEs, to change the point of view over time. But that's not going to be viable on the raw data, as the effect is not purely a translation of the image.

@sq7r0 the best I can propose is implementing this above (which is what NSMC does actually), using a bunch of data if you are able to record it (as svissr files, without decoding to images live). But as far as the raw imagery goes, that'll have to stay a "wontfix". Can't do much when it's the satellite itself.
