### ISSUE TITLE
demodulating verbose in satdump-ingestor?

### ISSUE THREAD

**Issue by bclswl0827** [altillimity/SatDump#188]
**What would you want to be added to satdump?**
satdump-ingestor returns more data (decoder, deframer, progress, fec, lock, etc.) than just SNR
**Describe the feature you'd like to have**
**Describe alternatives you've considered**
**Additional context**
satdump-ingestor can be useful when used as a backend of unmanned ground station, it should return the same amount of data as satdump-ui

**Comment by Aang23** [comment]
The ingestor is a not thing anymore. The feature is now in the main CLI app.
You may perhaps want to look into the stats server? That's a way for it to provide all status information over HTTP in a JSON format.

https://www.satdump.org/posts/basic-usage/#live-processing

**Comment by bclswl0827** [comment]
Great! I'm still using the old version, thanks for the quick response!
