### ISSUE TITLE
Log level, quiet mode and specifying the log output path

### ISSUE THREAD

**Issue by bclswl0827** [altillimity/SatDump#189]
**What would you want to be added to satdump?**
The `satdump.log` file is created every time as SatDump starts and the path can't be specified, it's better to make them customizable, it's also hoped that the log level can be customized.
Thanks for your attention!

**Describe the feature you'd like to have**
**Describe alternatives you've considered**
**Additional context**

**Comment by Aang23** [comment]
Indeed. That's some good ideas.

@ZbychuButItWasTaken thoughts? I would probably put that in satdump_cfg.json.

**Comment by ZbychuButItWasTaken** [comment]
Yeah

**Comment by Aang23** [comment]
Just added log level.

**Comment by Aang23** [comment]
And.. The log file can now be disabled in the config!
