### ISSUE TITLE
FY-4A LRIT live processing - Crashes when stopped

### ISSUE THREAD

**Issue by eswnl** [altillimity/SatDump#198]
**Description of the issue**
Stopping the live process causes Satdump to crash. But CADU file is created ok. Have to restart SatDump to decode it.
**Hardware (SDR/PC/OS)**
AirSpy R2
**Version (Eg, 1.0.0, CI Build #171)**
Ver 1.0.1

**Logs after the cras (satdump.logs)**

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
![image](https://user-images.githubusercontent.com/59115800/204072700-458e0c59-6dff-4555-adc5-31881d1dba39.png)

**Comment by Aang23** [comment]
Interesting... Let me see if I can reproduce.

**Comment by Aang23** [comment]
Fixed!
