### ISSUE TITLE
When Lime SDR is used in command line mode, its gain arguments don't seem to be functional

### ISSUE THREAD

**Issue by SV1CAL** [altillimity/SatDump#200]
**Description of the issue**
I may be missing something , but LIME SDR gain doesn't seem to change  from the command line using the arguments --lna_gain , --tia_gain , --pga_gain.

These arguments above are described here:
https://github.com/altillimity/SatDump/blob/master/docs/SDR-Options.md

Instead **--gain**  seems to work OK and sets the global gain ( as can be done with the vertical slider in HDSDR).

**Hardware (SDR/PC/OS)**
LimeSDR USB / Windows
**Version (Eg, 1.0.0, CI Build #171)**
1.0.1

Thanks !!!
Michael SV1CAL

**Comment by Aang23** [comment]
Hi!
Well that's normal, the right argument is --gain now, but I didn't update the documentation yet apparently.

**Comment by Aang23** [comment]
Edited the documentation.

**Comment by SV1CAL** [comment]
Thanks a lot  !
Regards ,
Michael
