### ISSUE TITLE
Add libomp-dev to install dependencies in readme

### ISSUE THREAD

**Issue by rtlsdrblog** [altillimity/SatDump#205]
Had to run `sudo apt-get install libomp-dev` to get the install to work on Ubuntu 22.04.1

**Comment by Aang23** [comment]
Interesting. I did not here. I will add something about it in the README.

**Comment by Aang23** [comment]
Done. It's weird though, because nobody else until now ever had this issue on 22.04. Perhaps you're using an older GCC version or similar? Though if OMP is not found, SatDump should simply not use it and succeed anyway.
