### ISSUE TITLE
Add NOAA APT support

### ISSUE THREAD

**Issue by lpmrfentazis** [altillimity/SatDump#206]
It would be great if satdump learned how to recive and decode NOAA APT. Now this usually happens through a bundle of Orbitron + sdrsharp + virtual audio cable + WXToImg, which works not stably. Satdump with the support of this technology would help a lot!

**Comment by Aang23** [comment]
Indeed. APT support has been requested quite a bit. It's been on the long-term todo for a while, but never a priority either... Though I think I'll take a bit of time to get that started soon enough - but won't give an ETA.

**Comment by K4KDR** [comment]
Many thanks for a least considering APT!

-Scott,  K4KDR

**Comment by Aang23** [comment]
No problem!
It wasn't really something I initially expected to have requests about honestly. I'm a bit surprised by how many people actually want it.

**Comment by Aang23** [comment]
Improved the sync. Only need to parse wedges now.
![raw](https://user-images.githubusercontent.com/23421917/205161583-ed282ae4-584c-448d-86e2-363e5be4c1b7.png)

**Comment by K4KDR** [comment]
Great!!  Can't wait to try tonight's NOAA passes.

Many thanks!

**Comment by Aang23** [comment]
As a note :
For now, it will work with basebands (like all other signals). It can also work with 16-bits WAV audio files often used in the APT decoding scene, but I didn't add the menu option for audio samplerate yet.

Hopefully it works OK for you!

**Comment by Aang23** [comment]
I did a bit more cleanup & changes. @K4KDR maybe do update in the meantime!

![avhrr_apt_A_Equalized](https://user-images.githubusercontent.com/23421917/205165962-91ddf599-241e-4347-a42b-b129c65b98c8.png)
![avhrr_apt_B_Equalized](https://user-images.githubusercontent.com/23421917/205165966-3572cbd3-da68-48a8-9a9f-593ec05b35bd.png)
![avhrr_apt_rgb_224](https://user-images.githubusercontent.com/23421917/205165970-1229f6bb-44d1-4391-876f-a3b9740a579c.png)

**Comment by K4KDR** [comment]
Will be sure to get the latest before tonight's passes.

Many thanks!!

**Comment by lpmrfentazis** [comment]
Wonderful! One of these days I will put the station on permanent duty for testing
