### ISSUE TITLE
The spectrum display broke in 1.0.3

### ISSUE THREAD

**Issue by lpmrfentazis** [altillimity/SatDump#219]
Just now I got around to testing live APT processing, but now I noticed that the spectrum and waterfall display does not work for me, the situation will be saved on different computers and sdr. As I understand it, the survey itself works, see screenshot 3-4.

AIRSPY SDR/ RTLSDR
Windows 10/11

1.0.3

There was no problem on 1.0.2.
![Screenshot_2](https://user-images.githubusercontent.com/43905097/208407368-916a57b3-f850-46e9-85e8-a004e8377fc2.png)
![Screenshot_1](https://user-images.githubusercontent.com/43905097/208407387-e773eca9-a4e2-4e68-a5a5-77e082b176c4.png)

For the test, I tried to run APT processing and spam with a walkie-talkie at the desired frequency, there is a reaction.

![image](https://user-images.githubusercontent.com/43905097/208408270-f63a55ff-4004-416d-a951-96269e2538cd.png)
![image](https://user-images.githubusercontent.com/43905097/208408287-a8efc28a-4e9c-4491-999c-c9085d10db0a.png)

**Comment by Aang23** [comment]
Well, first of all I would suggest you drag the "FFT Min" slider under the "FFT" Tab down. The default seems to high. Might as well lower it as it confused a few people.

**Comment by lpmrfentazis** [comment]
> Ну, во-первых, я бы посоветовал вам перетащить ползунок «FFT Min» на вкладке «FFT» вниз. Значение по умолчанию кажется высоким. С тем же успехом можно было бы и понизить, так как это смутило нескольких человек.

Yes, but it doesn't seem to cancel the problem?

**Comment by Aang23** [comment]
What do you see when you do that? Set it to be on the left, down to -120 or such?

**Comment by lpmrfentazis** [comment]
Oh, it really seems to work.. And what could be the reason for such a difference in the displayed level with the same settings on different versions?
![image](https://user-images.githubusercontent.com/43905097/208440647-af1f277a-d6f9-4da5-ba0e-87f9e6b74118.png)
It turned out to be quite unexpected for me.

**Comment by Aang23** [comment]
Play around with the FFT Max / Min settings, and perhaps the FFT Rate and Avg as well. Everything was modified so you will want to tune it etc.

I'll also take some feedback if you think some things don't work as they should!

**Comment by lpmrfentazis** [comment]
> Play around with the FFT Max / Min settings, and perhaps the FFT Rate and Avg as well. Everything was modified so you will want to tune it etc.
> 
> I'll also take some feedback if you think some things don't work as they should!

In general, this does not apply to this issue, but when I build satdump on Ubuntu sources or install the apk on Android, SDRs are not detected, what could this be related to? That is, when connected, they simply do not appear in the list.
