### ISSUE TITLE
Add the current level in Db to the status server

### ISSUE THREAD

**Issue by lpmrfentazis** [altillimity/SatDump#227]
**What would you want to be added to satdump?**
Hi! If it's not too difficult, I would like the status server to also transmit the current level. That is, in other words, not only the signal level above the noise, but also the noise level itself in Db.  This would allow me to integrate SatDump into an already existing system and get rid of the terrible SoapySDR scripts. The I level allows you to monitor the status of the signal line, LNA, and so on.![image](https://user-images.githubusercontent.com/43905097/210235148-d737e3c7-33b8-42ff-9fa2-28ef8cd974db.png)

![image](https://user-images.githubusercontent.com/43905097/210235504-7d20be8b-ecfc-4281-9aeb-4347653a4aa9.png)

![image](https://user-images.githubusercontent.com/43905097/210235652-9530676d-708b-4865-af9d-f3d5df5472e5.png)

**Comment by Aang23** [comment]
Would a solution similar to #199 where I would include a FFT in the stats (optionally) work for you?

**Comment by lpmrfentazis** [comment]
> Would a solution similar to #199 where I would include a FFT in the stats (optionally) work for you?

To be honest, I read this thread again, but in the end I didn't fully understand what the final version was planned.

Is it about streaming part of the spectrum ? In what form will the fft be transmitted?
For the most part, I am only interested in one number showing the noise level, in addition to the signal level.

**Comment by Aang23** [comment]
You can now get the FFT values in stats if you enable the option. This works in both live and record mode.

--fft_enable // To enable it
--fft_size // Set FFT size, default 512
--fft_rate // Set FFT rate, default 30 per second
--fft_avg / Set FFT Avg rate

![Screenshot from 2023-01-05 23-06-30](https://user-images.githubusercontent.com/23421917/210893150-9e1d661e-7efc-4c6e-9a1e-2e37e6c58ac8.png)
