### ISSUE TITLE
Raspberry Pi install

### ISSUE THREAD

**Issue by ve3elb** [altillimity/SatDump#39]
Hello everyone can someone point me to the step by step installation guide for Raspberry Pi with SatDump GUI

Will the Mac OS install guide work on the Raspberry Pi. That's a lot of steps lol. Can someone make one or more install scripts that will that will do a full GUI install making it easier for those who don't know much about Linux wanted to try.

I have complied and built an easy setup disk image of Raspberry NOAA V2 for Raspberry Pi. And many many user have been using it because they don't have to do all of the compiling and install.  I would like to do the same with SatDump so we can get other users. Compiling and building the various disk images gives everyone a change to try the different software available plus many are moving over to Linux. Raspberry Pi's are getting used more more these days as weather satellite stations. ￼ 

Thank you.

**Comment by Aang23** [comment]
I think this can be closed.
