### ISSUE TITLE
LRPT Locking issues (RS, Demod?) (M2 LRPT)

### ISSUE THREAD

**Issue by K4KDR** [altillimity/SatDump#44]
This is very repeatable and I have not been able to find a cause.

System is Ubuntu 18.04, SatDump v0.0.37, "Live processing" option for Meteor-M2 137 MHz LRPT, Airspy-R2 @ 2.5M Samplerate

When satdump-ui GUI interface is launched, all appears well.  At AOS, the signal on the FFT grows & grows as elevation increases.  Viterbi turns green & the 4-dot constellations look normal.  However, no matter how strong the signal or how long you wait, Reed-Solomon will stay red & there is no decode.

![rs-red](https://user-images.githubusercontent.com/19886368/135174208-bd28711e-5512-45fd-a9ff-f1f5fc53520c.png)

However, if you un-check "Finish processing" and click "Stop", the click "Start" to restart the live capture, Reed-Solomon immediately turns green & images decode & are processed normally.

![rs-green](https://user-images.githubusercontent.com/19886368/135174269-6c463ed2-6ad3-4dad-a759-aa98138d971c.png)

Any suggestions on how I might be able to stop using this work-around much appreciated!

**Comment by Aang23** [comment]
@K4KDR, do you think you could record a baseband once and share it? (Using the same settings / etc). I will then try to reproduce the issue on my side.

There was a bug like that back before I released anything, but it is supposed to be fixed...

@marianzb this appears to be a RTL-TCP issue. Mind opening another issue about this?

**Comment by K4KDR** [comment]
I assume you mean a recording when it is NOT locked?  

Yes, will do!    Just to be clear, is it the .CADU file you are looking for?

Thanks!

**Comment by Aang23** [comment]
No, I meant a baseband (maybe preferrably using SatDump's recorder in f32 mode, as it uses the same DSP chain). That way I can feed it back into the demod / decode and see where something fails / etc.

**Comment by K4KDR** [comment]
I spoke too soon - I can record a 32-bit .raw I/Q with GQRX, but I have no idea how to "us(e) SatDump's recorder in f32 mode".

Any guidance appreciated!

**Comment by Aang23** [comment]
Oh right, I did not release the recorder in 0.0.37... So either use the current source on Git or GQRX, should do too since I doubt the issue lies in the SDR part.

**Comment by AlexandreRouma** [comment]
Without looking at the code I bet the incoming data bytes get desyncronized and that causes the Q value from one sample to be read with the I value of the next sample. This won't have much effect on the constellation but will mess up the symbols

**Comment by Aang23** [comment]
Wait, @K4KDR, could you also see if enabling DC Blocking helps? Some R2 units (mostly older ones it seems) sometimes had some I/Q offset that could effectively cause this kind of issues. If it's the case it wouldn't be too hard to fix at least.

**Comment by K4KDR** [comment]
Very glad to enable the 'DC Block' option.  I normally do not since the Airspy doesn't have that issue.   I'll have that checked on future passes just to see if this issue does or does not continue.  Thanks!

**Comment by K4KDR** [comment]
Well, it's only one attempt but on tonight's M2 pass (w/ 'DC Block' enabled), SatDump achieved RS-Lock without having to be restarted.  I will continue to use the 'DC-Block' option to see if that continues to give me a lock when SNR is good.

![dc-block-on](https://user-images.githubusercontent.com/19886368/137820675-de5752ca-1543-4b0a-9e67-84e1ea29574a.png)

![satdump](https://user-images.githubusercontent.com/19886368/137820711-b18fe152-81e4-4862-a0dd-8d6308eb6752.png)

**Comment by K4KDR** [comment]
[v0.0.38 / master branch / build: 01a8276, built from source]

Running 'Live Processing' with Airspy-R2 @ 2.5M Sample Rate:

On the **first live Meteor-M2 LRPT pass** with this build,  the **Reed-Solomon** indicator locked green without having to stop & re-start the GUI.   However, since this was an intermittent issue, I will continue to monitor the situation & verify that it locks each time without the need for a stop & re-start.   Thanks very much for the updates!

![GUI](https://user-images.githubusercontent.com/19886368/140610275-45512b2f-be43-4c23-a65b-70d3ceb9d502.png)

**Comment by marianzb** [comment]
it looks my problem with RS locking was caused by some jitter on rtl-tcp server. Recently I have reinstalled Raspberry Pi there and now live decoding works perfectly all indicators green. :-) Also updated latest version, thanks for updating this project!

**Comment by Aang23** [comment]
RTL-TCP has this kind of issue pretty often... So not too surprised it was that.

I guess this can be closed now!
