### ISSUE TITLE
v0.0.38 no values for 'SNR' or 'Peak SNR' displayed

### ISSUE THREAD

**Issue by K4KDR** [altillimity/SatDump#58]
Since the upgrade to v0.0.38, there are no values for 'SNR' or 'Peak SNR' in the 'Signal' box (QPSK Demodulator window)

[System:   Ubuntu 18.04, Satdump build master / g463f45f]

![satdump-no-snr-display](https://user-images.githubusercontent.com/19886368/139561949-22f171ad-6149-4f5d-9011-474a4213e3bc.png)

Thanks!   -Scott,  K4KDR

**Comment by Aang23** [comment]
That is weird... Though that constellation looks very wrong as well. Would you be able to record a baseband? Is that local noise causing this?

**Comment by K4KDR** [comment]
Glad to!  Just looked at the 'Baseband Recorder' tab in v0.0.38 for the first time... seems that it runs with both 10M and 2.5M sample rates, so only the 'Live Processing' tab crashes with 2.5M.

Would you like the Recording with the 'i8', 'i16', or 'f32' option.  2.5M or 10M sample rate?

Thanks!

**Comment by K4KDR** [comment]
Please disregard my last question - tonight's Meteor-M2 pass is here, so I'll record using 2.5M in the i16 format.

**Comment by K4KDR** [comment]
Ok, baseband recorded but at 3.8G, I would need overnight to upload it so please let me know if that might be of any use to you.   As usual for M2, the signal looked great tonight & the baseband recorder worked perfectly at the 2.5M sample rate:

![baseband-record](https://user-images.githubusercontent.com/19886368/139758209-e8eec330-8dea-483e-af96-a893de1009b6.png)

... and the resulting image (just a bit cropped off the top & bottom) turned out just about perfect.  While the 'Live Processing' option is fun, I certainly have no problem recording & then using the 'Offline Processing' tab to generate the images!

![MSU-MR-5-EQU-CORRECTED-crop](https://user-images.githubusercontent.com/19886368/139758400-ca7bb34e-69a0-4441-96fa-004d6cfc8dc2.png)

**Comment by Aang23** [comment]
> Glad to! Just looked at the 'Baseband Recorder' tab in v0.0.38 for the first time... seems that it runs with both 10M and 2.5M sample rates, so only the 'Live Processing' tab crashes with 2.5M.
> 
> Would you like the Recording with the 'i8', 'i16', or 'f32' option. 2.5M or 10M sample rate?
> 
> Thanks!

i8 would suffice I'd say.

Good that it worked from baseband, but it pretty much makes it even weirder. It should work live, by all means...

Would you be able to upload the baseband?

**Comment by K4KDR** [comment]
Thank you for the follow-up!

For the past few days, I have been getting perfect images after recording a baseband & then using the Offline Processing tab.  Tonight, however, even though the SNR was fine, the recording did not produce any signal lock or images. 

![baseband-recording-GUI](https://user-images.githubusercontent.com/19886368/140591715-e61e6e77-9009-437f-b3b4-cc06c798354e.png)

... however, this is the first time I have tried an 'i8' recording - all of my previous successful attempts were with the 'i16' format.  

Tonight's i8 recording is available at:

https://www.qsl.net/k/k4kdr//iq/meteor-m2/00-00-27_2500000SPS_137100000Hz.zip

Thanks very much!

-Scott,  K4KDR

**Comment by K4KDR** [comment]
[v0.0.38 / master branch / build: 01a8276, built from source]

Running 'Live Processing' with Airspy-R2 @ 2.5M Sample Rate:

**SNR** & **PEAK SNR** values displayed correctly - thank you!!

![GUI](https://user-images.githubusercontent.com/19886368/140610161-6ad39df6-6af7-4b27-ae29-e5b5d0c4034e.png)

**Comment by Aang23** [comment]
Awesome! As a note, https://github.com/altillimity/SatDump/commit/a92e595a0993430b5e43625b25700b09849839f8 should also affect this issue, in theory.
I've finally figured that one out after LazzSnazz had issues on GOES-R HRIT.

**Comment by K4KDR** [comment]
Very good - will continue to update to the latest.

Many thanks!

**Comment by andriux26** [comment]
Who will help with the command need live build
-DBUILD_LIVE=ON
cmake -DCMAKE_BUILD_TYPE=Release ..                             # MacOS
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .. #
How correct enter

**Comment by Aang23** [comment]
> Who will help with the command need live build -DBUILD_LIVE=ON cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .. # How correct enter linux

I replied in your issue. Please carry on in there if you have any other questions, this is not what this one is about...

**Comment by Aang23** [comment]
By the way @K4KDR, have you ever had that issue again? If not, I think I will close this.

**Comment by andriux26** [comment]
Fanks for you  hepl i launch satdump live you can closed

2021 m. lapkr. 19 d., pn 15:47, Aang23 ***@***.***> rašė:

**Comment by K4KDR** [comment]
No, with the latest builds I seem to be ok on that.  Thanks so much - ok to close!
