### ISSUE TITLE
Update build instructions to use libvolk2

### ISSUE THREAD

**Issue by errolt** [altillimity/SatDump#61]
Hi Aang23,

LibVolk1 has been depreciated in some Linux distros, like Ubuntu 20.04. You can force an install by downloading the deb, but that seems to break other other apps, like gnuRadio.

Using libvolk2-dev to build SatDump seems to work fine and doesn't cause issues with the rest of the system.

Please update the build instructions to either specify the libvolk2-dev package, or add a note that libvolk2-dev can be installed if libvolk1-dev isn't available.

Thank you,
Errol

**Comment by Aang23** [comment]
Hi!
The only required is Volk, any version from 1 to the latest on Github will do just fine. Main reason it is libvolk1-dev in the guide is most distros still chip with it, and lack libvolk2-dev.

Adding such a notice is definitely the way to go.

You're welcome!
