### ISSUE TITLE
Android samplerate problem

### ISSUE THREAD

**Issue by funnymdzz** [altillimity/SatDump#66]
I want to use 6000000HZ samplerate for fy-2h decode on android  but when I set the samplerate to 6000000HZ the output was like this even though set it to 10000000HZ. the BPSK demod constellation is slow.use a lower samplerate like 2500000HZ is working but the SNR is reduced.
![FY-2x_3_20211109T115509Z](https://user-images.githubusercontent.com/25901780/141478327-a34d6ece-964a-4f9e-9835-32c2f6ed6080.png)

**Comment by funnymdzz** [comment]
SDR is Airspy One

**Comment by funnymdzz** [comment]
almost forget it is live processing

**Comment by Aang23** [comment]
What device are you using?

**Comment by Aang23** [comment]
This honestly just looks like sampledrop due to an older drive or too much stuff running in the background to me. Is that an airspy R2 or Mini though?

**Comment by funnymdzz** [comment]
> This honestly just looks like sampledrop due to an older drive or too much stuff running in the background to me. Is that an airspy R2 or Mini though?

it is a airspy one and in the pc it is no problem when I use high samplerate

**Comment by Aang23** [comment]
Yes, but it's not because your PC does it fine your phone will. They are different hardware and for many reasons it could not be performing the same.
