### ISSUE TITLE
live elektro L TLM fail

### ISSUE THREAD

**Issue by miguelvrr** [altillimity/SatDump#68]
Hi, I have already the newest build for win with the live processing aparently working. Satdump is able to open my airspy but the elektro L TLM signal is non present. I can't decode anything and the signal stays on 0.0 Any idea how to configure the software to receive this?? All help is welcome! Thx

**Comment by Aang23** [comment]
Hi, do you have a screenshot of the issue?

**Comment by miguelvrr** [comment]
Hi sir,
Yes i sent you the prints in attachment. Still not able to decode any signal.
Is the sat still active and transmitting in 1693? The 1544 beacon seems to be working fine.

0![print_satdump_2](https://user-images.githubusercontent.com/9042023/142728203-43a486c7-2e13-4415-84b2-33387b557879.png)
![print_satdump](https://user-images.githubusercontent.com/9042023/142728206-a0f50d76-4418-4733-a5dd-26313880f9cf.png)

**Comment by errolt** [comment]
@miguelvrr 
For me it works. But my signal is weak, so locking is a problem.
![image](https://user-images.githubusercontent.com/6266552/142996485-61a02f3e-ce1b-477c-8f59-aca9017efb1d.png)

**Comment by Aang23** [comment]
https://github.com/altillimity/SatDump/commit/6d0de5d8255e841b8f7cc230efce39927748d598 should have helped a lot with this issue.
