### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by andriux26** [altillimity/SatDump#69]
> Who will help with the command need live build -DBUILD_LIVE=ON 
 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .. # 
How correct enter in linux

**Comment by Aang23** [comment]
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_LIVE=ON ..

I should improve the readme...
