### ISSUE TITLE
[Win32] Exiting by "Alt-F4"

### ISSUE THREAD

**Issue by gvanem** [altillimity/SatDump#70]
When running e.g. the "*BasebandRecorder*" and exiting by pressing **Alt-F4**, 
the `satdump-ui.exe` hangs forever. 

*Edit*: Same issue when simply mouse-pressing the upper-right **X**.

The last log is:
```
  (I) Saving settings to file settings.json
```

Some event is blocking (?) to continue the exit. Or perhaps an issue with ImGui?

Pressing **Exit** first, then pressing **Alt-F4** (or mouse-pressing the upper-right **X**), works fine.

**Comment by Aang23** [comment]
A commit I have pushed a few moments ago addresses a similar issue for live processing. Let me fix this for the recorder right now.

**Comment by Aang23** [comment]
Fixed!

**Comment by gvanem** [comment]
That was fast!! Work fine now.
