### ISSUE TITLE
Disable satdump-ingestor if NOGUI set?

### ISSUE THREAD

**Issue by errolt** [altillimity/SatDump#73]
Hi Aang23,

Sorry about logging all these issues.

https://github.com/altillimity/SatDump/blob/7022d0e5eb6f2f544a31f5b7382356e00e2fc8d5/CMakeLists.txt#L19-L21

This line disables the cli satdump-ingestor if NOGUI=ON is set during the cmake phase? 

Even if NOGUI is set the command line live processing should still be available? 

Thank you,
Errol

**Comment by Aang23** [comment]
That's an oversight... That was used back when live was only available in the UI version and before I introduced other macros.
Thanks a lot for reporting!
