### ISSUE TITLE
v0.0.39 not equal MASTER?

### ISSUE THREAD

**Issue by K4KDR** [altillimity/SatDump#80]
Thanks for another round of updates!

I should not 'assume', but when **v0.0.39** was announced I thought that I would be updated to the latest version with a 'git pull' and rebuild from the MASTER branch.

I see that is **not** the case - after 'git pull' & rebuild, MASTER still shows v0.0.38 when run.

Is there any way to know when the MASTER branch repository is the same as the latest announced "release"?

Many thanks!

-Scott,  K4KDR

**Comment by K4KDR** [comment]
I believe I found the issue.

Even when downloading & building the v0.0.39 release tar, the app still displays v0.0.38 when run.

So, it seems that it might just be a cosmetic issue with the version stamp within the application.

Thanks!

-Scott

**Comment by Aang23** [comment]
Indeed... I somehow entirely forgot to bump the version in the code itself... Oh well, I'll fix that up in Git and it probably isn't such a big deal I'd say. Happens.
Thanks though!
