### ISSUE TITLE
Incompatible with LeanHRPT Demod

### ISSUE THREAD

**Issue by zeke800** [altillimity/SatDump#92]
Hi, thanks for the great software! 

I live-demoded a Meteor pass using LeanHRPT-Demod. When I set the file to process in Satdump, it completely is unable to decode it and outputs some weird lines. When I run the file through LeanHRPT-Decode it processes perfectly with almost 4000 clear lines. I opened an issue and the author mentioned that 

> Frankly this is a SatDump issue, there is no purpose in using soft symbols for NOAA/Meteor, since it gets sliced into binary one step later anyway (what LeanHRPT-Demod outputs).

So I recorded a MetOp pass, which (I think) uses QPSK. Satdump outputed empty/corrupted files. How can I fix this?

Thank you so much!

Satdump output:
![MSU-MR-4-EQU](https://user-images.githubusercontent.com/82127189/151864508-92bedc16-a208-412b-ae58-0ba7fb8718e3.png)

LeanHRPT output:
![meteorjan23 (reduced resolution)](https://user-images.githubusercontent.com/82127189/151864585-6c8b45b5-d88e-4183-9302-92555db11186.png)

**Comment by Aang23** [comment]
> I live-demoded a Meteor pass using LeanHRPT-Demod. When I set the file to process in Satdump, it completely is unable to decode it and outputs some weird lines. When I run the file through LeanHRPT-Decode it processes perfectly with almost 4000 clear lines. I opened an issue and the author mentioned that

The software does not utilize the standard file formats SatDump and most other software you will find online uses. It looks like a different frame period or such to me, but I will not be changing everything to support this.

> Frankly this is a SatDump issue, there is no purpose in using soft symbols for NOAA/Meteor, since it gets sliced into binary one step later anyway (what LeanHRPT-Demod outputs).

This has nothing to do with softs symbols, which are used not to have multiples demods. Soft symbols are not written to a file anyway, and pushed directly into the decoder for further processing as soft symbols are directly suitable for any further decoding steps.

So in the end, all I am going to say is : 
Either convert your files to a supported format, or use SatDump for previous processing steps as well.
