### ISSUE TITLE
SOLVED ! no longer updates the TLEs, from Satdump update TLE

### ISSUE THREAD

**Issue by IZ5RZR** [altillimity/SatDump#95]
Hello Altillimity
Thanks for this great software
For a couple of days the program no longer updates the TLEs, while through ORBITRON I noticed that the TLEs are downloaded from celestrack.com.
Is it possible that some links have changed?, can you fix it?
Hello
IZ5RZR

**Comment by Aang23** [comment]
Do you have the logs on hand? It's been fine on my end.

**Comment by Robydem** [comment]
Hello, same problem, it does not update the data from celestrack.com. tnx

**Comment by IZ5RZR** [comment]
> Do you have the logs on hand? It's been fine on my end.

Actually not, but problem still persist.
You can try it windows version 0039, tle wont download
erros is can't fetch tle data.
The only way to update manually is edit old tle from resources\tle folder and search number of satellite in celestrack, copy tle data and paste in correct file in TLE satdump folder

**Comment by IZ3ZLU** [comment]
![Immagine](https://user-images.githubusercontent.com/22505704/156304370-b0bf1fdf-5667-4eb0-9173-cf56fdce0287.jpg)

**Comment by IZ3ZLU** [comment]
Spero di no..... poveretto.....

Il mer 2 mar 2022, 16:12 Max ***@***.***> ha scritto:

**Comment by IZ5RZR** [comment]
> Hello, same problem, it does not update the data from celestrack.com. tnx

Bug still continue. No TLE update with windows systems

**Comment by x31415926** [comment]
It seems the configured TLE address (from json) returns HTTP moved permanently. The new location, as far as I can see is https://www.celestrak.com/NORAD/elements/gp.php?CATNR=

As an aside, when/if someone fixes this, might as well fix this line as well since the formatting for spdlog doesn't use the C formatters. 
logger->error("HTTP Server Responded: %d %s", nng_http_res_get_status(res), nng_http_res_get_reason(res));

**Comment by IZ5RZR** [comment]
Hello! Fix working good by copy TLE.Json from repository to  Satdump resources folder.
Instead I have make a simply batch script for windows 10 to update tle to run in satdump resources tle folder
[run - SatdumpTLE.zip](https://github.com/altillimity/SatDump/files/8529570/run.-.SatdumpTLE.zip)
